### ISSUE TITLE
Specify font to use with RIME on Linux

### ISSUE THREAD

**Issue by dosssman** [rime/ibus-rime#106]
Greetings.

Thanks for open-sourcing this library.

Is there any way to configure the font that is used by ibus-rime to display the characters ?
I happen to have some Japanese font installed too, and they seem to override the Chinese fonts, so I would like to specify which font to use to RIME.

It seems to be possible using either `squirrel` or `weasel`, but I am on a native Linux system, and adding using config specification in the lines of:
```
# ibus_rime.yaml
style:
  font_face: "Souce Han Sans CN"
  font_size: 14
```
unfortunately does not seem to work.

Is there any other alternative to achieve the desired results ?

Thanks in advance for your time.
