### ISSUE TITLE
[bug] speller/algebra rules affect all schemas that use the same dictionary

### ISSUE THREAD

**Issue by rodrigomorales1** [rime/ibus-rime#184]
- [Description of the bug](#orgd4e7d60)
- [Experiment 1](#org7477900)
- [Experiment 2](#org88b625b)
- [System information](#org0e1222e)

<a id="orgd4e7d60"></a>

# Description of the bug

When two schemas use the same dictionary, the rules in the key `speller/algebra` in one schema also become part of the other schema.

In "Experiment 1" below, I created two schemas that used the same dictionary. The rules in `speller/algebra` in one of the schemas affected the other schema.

In "Experiment 2" below, I created two schemas that used different dictionaries. The rules in `speller/algebra` in one of the schemas didn't affect the other schema.

<a id="org7477900"></a>

# Experiment 1

I executed `$ rm -rf ~/.config/ibus/rime && mkdir ~/.config/ibus/rime` to remove all files in `~/.config/ibus/rime` to avoid any other file interfer with this experiment.

`~/.config/ibus/rime/my.dict.yaml` (see code block below)

```yaml
---
name: my
version: 1
sort: original
...
111	insertone
222	inserttwo
333	insertthree
444	insertfour
```

`~/.config/ibus/rime/foo.schema.yaml` (see code block below)

```yaml
schema:
  schema_id: foo
  name: Schema foo
  version: 1

engine:
  processors:
  - ascii_composer
  - selector
  - key_binder
  - speller
  - selector
  - navigator
  - express_editor
  segmentors:
  - ascii_segmentor
  - abc_segmentor
  - punct_segmentor
  - fallback_segmentor
  translators:
  - table_translator

speller:
  alphabet: "abcdefghijklmnopqrstuvwxyz"
  auto_select: false

translator:
  dictionary: my

key_binder:
  import_preset: default
```

`~/.config/ibus/rime/bar.schema.yaml` (see code block below)

```yaml
schema:
  schema_id: bar
  name: Schema bar
  version: 1

engine:
  processors:
  - ascii_composer
  - selector
  - key_binder
  - speller
  - selector
  - navigator
  - express_editor
  segmentors:
  - ascii_segmentor
  - abc_segmentor
  - punct_segmentor
  - fallback_segmentor
  translators:
  - table_translator

speller:
  alphabet: "abcdefghijklmnopqrstuvwxyz"
  algebra:
    - xform/insert/h/
  auto_select: false

translator:
  dictionary: my

key_binder:
  import_preset: default
```

`default.custom.yaml` (see code block below)

```yaml
patch:
  schema_list:
  - schema: foo
  - schema: bar
```

I executed `ibus-daemon -drx`.

I opened `gedit`.

I pressed `F4` to select the input method. I selected `Schema foo`. I pressed `h` and the candidate list was shown. This is unexpected behavior.

The screenshot below shows the behavior when using `Schema foo` and pressing `h`.

![image](https://github.com/rime/ibus-rime/assets/74389646/270a5ee0-0bf1-489f-b1e7-7ac75ad2d461)

The screenshot below shows the behavior when using `Schema bar` and pressing `h`.

![image](https://github.com/rime/ibus-rime/assets/74389646/73acaaa1-c368-4f35-8e3c-670c701183fa)

I believe this is unexpected behavior (i.e. it shouldn't happen) because in `Schema foo`, there is no input that starts with `h`. It seems that RIME mistakenly considers the rule `speller/algebra` from `Schema bar`. This situation doesn't happen when both schemas use separate dictionaries. See section "Experiment 2".

<a id="org88b625b"></a>

# Experiment 2

As in the previous experiment, I executed `$ rm -rf ~/.config/ibus/rime && mkdir ~/.config/ibus/rime` to remove all files in `~/.config/ibus/rime` to avoid any other file interfer with this experiment.

`~/.config/ibus/rime/foo.dict.yaml` (see code block below)

```yaml
---
name: foo
version: 1
sort: original
...
111	insertone
222	inserttwo
333	insertthree
444	insertfour
```

`~/.config/ibus/rime/foo.schema.yaml` (see code block below)

```yaml
schema:
  schema_id: foo
  name: Schema foo
  version: 1

engine:
  processors:
  - ascii_composer
  - selector
  - key_binder
  - speller
  - selector
  - navigator
  - express_editor
  segmentors:
  - ascii_segmentor
  - abc_segmentor
  - punct_segmentor
  - fallback_segmentor
  translators:
  - table_translator

speller:
  alphabet: "abcdefghijklmnopqrstuvwxyz"
  auto_select: false

translator:
  dictionary: foo

key_binder:
  import_preset: default
```

`~/.config/ibus/rime/bar.dict.yaml`

```yaml
---
name: bar
version: 1
sort: original
...
111	insertone
222	inserttwo
333	insertthree
444	insertfour
```

`~/.config/ibus/rime/bar.schema.yaml` (see code block below)

```yaml
schema:
  schema_id: bar
  name: Schema bar
  version: 1

engine:
  processors:
  - ascii_composer
  - selector
  - key_binder
  - speller
  - selector
  - navigator
  - express_editor
  segmentors:
  - ascii_segmentor
  - abc_segmentor
  - punct_segmentor
  - fallback_segmentor
  translators:
  - table_translator

speller:
  alphabet: "abcdefghijklmnopqrstuvwxyz"
  algebra:
    - xform/insert/h/
  auto_select: false

translator:
  dictionary: bar

key_binder:
  import_preset: default
```

`~/.config/ibus/rime/default.custom.yaml` (see code block below)

```yaml
patch:
  schema_list:
  - schema: foo
  - schema: bar
```

I executed `ibus-daemon -drx`.

I opened `gedit`.

I pressed `F4` to select the input method. I selected `Schema foo`. I pressed `h` and the candidate list was not shown. This is expected behavior.

The screenshot below shows the behavior when using `Schema foo` and pressing `h`.

![image](https://github.com/rime/ibus-rime/assets/74389646/40c6601c-4330-4ed6-9bf2-10a8e19f86c4)

The screenshot below shows the behavior when using `Schema bar` and pressing `h`.

![image](https://github.com/rime/ibus-rime/assets/74389646/c6a824b3-5dbb-47f1-bb5c-d91d84db3425)

<a id="org0e1222e"></a>

# System information

-   Operating system: Ubuntu 22.04.4 LTS
-   ibus-rime version: 1.5.0-1 (amd64) (installed via `$ sudo apt install ibus-rime`)

PS: Please let me know if (1) this is indeed a bug or (2) I have misunderstood some functionality of RIME.
