### ISSUE TITLE
UI好像不正常/皮肤无法设置/debian/难道是我的设置不正确？

### ISSUE THREAD

**Issue by dist1** [rime/ibus-rime#77]
大家好啊！

我按照指示在 `..config/ibus/rime` 新建了一个文件 `default.custom.yaml` ，内容如下：

```yaml
example:
  name: test1
  author: test1
  back_color: 0xFFFFFF
  border_color: 0x000000
  text_color: 0xFFFFFF
  hilited_text_color: 0xFFFFFF
  hilited_back_color: 0xDDDDDD
  hilited_candidate_text_color: 0x000000
  hilited_candidate_back_color: 0xFFFFFF
  candidate_text_color: 0xFFFFFF
  comment_text_color: 0xFFFFFF
```

然后按了部署，然而好像没效果……

![zsmmssa](https://user-images.githubusercontent.com/1416332/62421766-88c0b580-b6d9-11e9-9e59-09099f4ab35f.png)

  * 配色没达到预期
  * 首候选词一片黒

这是为啥呢……要怎么办呢……
