### ISSUE TITLE
微软双拼分号会直接上屏

### ISSUE THREAD

**Issue by ghostry** [rime/ibus-rime#86]
方案是,从apt安装的
```
schema:
  schema_id: double_pinyin_mspy
  name: MSPY雙拼
  version: "0.15"
  author:
    - 佛振 <chen.sst@gmail.com>
  description: |
    朙月拼音＋MSPY雙拼方案。
  dependencies:
    - stroke
```

比如输入英语,y;yu,在输入y;后就会把第一个候选词上屏,变成输入了 要;
