### ISSUE TITLE
plum rime-install then maintenance causes no effect on Ubuntu

### ISSUE THREAD

**Issue by danvim** [rime/ibus-rime#88]
Upon installing ibus-rime I tried using rime-install to patch rime. Then after "部署", the patches causes no effect. I discovered that inside `~/.config` there is no longer a `default.yaml` in Ubuntu 19.10. I used to manually edit this file to apply my list of schemas and `menu/page_size:9` in Ubuntu 18.04, when rime-install didn't have an effect on the deployment of rime then either. It just downloaded the required files to `~/.config`.

default.custom.yaml

```yaml
__patch:
# Rx: custom:add:schema=ipa_yunlong {
  - patch/+:
      schema_list/+/+:
        - schema: ipa_yunlong
# }
# Rx: custom:clear_schema_list: {
  - patch/+:
      schema_list: []
# }
```

This is my second page of <kbd>Ctrl+`</kbd>.

![image](https://user-images.githubusercontent.com/5255292/72868906-66b9fe80-3d1e-11ea-8239-4d25a8a22dc3.png)
