### ISSUE TITLE
不能绑定按键@

### ISSUE THREAD

**Issue by yzy-1** [rime/ibus-rime#89]
我的 `default.custom.yaml` 如下:

```
patch:
  "menu/page_size": 5
  "key_binder/bindings":
    - {accept: numbersign, send: 1, when: has_menu}
    - {accept: at, send: 2, when: has_menu}
    - {accept: less, send: 3, when: has_menu}
    - {accept: greater, send: 4, when: has_menu}
    - {accept: bracketleft, send: 5, when: has_menu}
    - {accept: bracketright, send: 6, when: has_menu}
    - {accept: braceleft, send: 7, when: has_menu}
    - {accept: braceright, send: 8, when: has_menu}
    - {accept: parenleft, send: 9, when: has_menu}
    - {accept: parenright, send: 0, when: has_menu}
    - {accept: minus, send: Page_Up, when: has_menu}
    - {accept: equal, send: Page_Down, when: has_menu}
  "ascii_composer/switch_key":
    Caps_Lock: clear
    Control_L: noop
    Control_R: noop
    Eisu_toggle: clear
```

只有 `- {accept: at, send: 2, when: has_menu}` 一句不起作用, 其他的映射都起作用, 我没有在 /tmp 文件夹下看到任何错误日志

```
uname -r: 5.5.2-arch-1-1
ibus version: IBus 1.5.21
```
