### ISSUE TITLE
自定义配置不生效

### ISSUE THREAD

**Issue by ywxt** [rime/ibus-rime#94]
- 发行版：Manjaro 19
- 输入法：ibus
-  路径：~/.config/ibus/rime
-  文件名：default.custom.yaml
- 内容：
```yaml
patch:
  "style/display_tray_icon": true
  "style/horizontal": true #横排显示
  "style/font_face": "Microsoft YaHei" #字体
  "style/font_point": 13 #字体大小
  "style/inline_preedit": true # 嵌入式候选窗单行显示


  "style/layout/border_width": 0
  "style/layout/border": 0
  "style/layout/margin_x": 12 #候选字左右边距
  "style/layout/margin_y": 12 #候选字上下边距
  "style/layout/hilite_padding": 12 #候选字背景色色块高度 若想候选字背景色块无边界填充候选框，仅需其高度和候选字上下边距一致即可
  "style/layout/hilite_spacing": 3 # 序号和候选字之间的间隔
  "style/layout/spacing": 10 #作用不明
  "style/layout/candidate_spacing": 24 # 候选字间隔
  "style/layout/round_corner": 0 #候选字背景色块圆角幅度


  "style/color_scheme": Micosoft
  "preset_color_schemes/Micosoft":
    name: "Micosoft"
    author: "XNOM"
    back_color: 0xffffff #候选框 背景色
    border_color: 0xD77800 #候选框 边框颜色
    text_color: 0x000000 #已选择字 文字颜色
    hilited_text_color: 0x000000 #已选择字右侧拼音 文字颜色
    hilited_back_color: 0xffffff #已选择字右侧拼音 背景色
    hilited_candidate_text_color: 0xffffff #候选字颜色
    hilited_candidate_back_color: 0xD77800 #候选字背景色
    candidate_text_color: 0x000000 #未候选字颜色
```
